steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/priyamsolanki643-glitch/fp:$COMMIT_SHA', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/priyamsolanki643-glitch/fp:$COMMIT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'gcr.io/$PROJECT_ID/github.com/priyamsolanki643-glitch/fp:$COMMIT_SHA'
